export const GAME_WIDTH = 1280;
export const GAME_HEIGHT = 720;

export const WORLD_WIDTH = 2000;
export const WORLD_HEIGHT = 1400;

export const PLAYER_SPEED = 260;
export const PLAYER_MAX_HP = 100;
export const PLAYER_HIT_INVULNERABILITY_MS = 700;
export const PLAYER_HIT_FLASH_MS = 120;
export const PLAYER_PICKUP_RANGE = 90;
export const PLAYER_START_LEVEL = 1;
export const PLAYER_START_XP_TO_NEXT_LEVEL = 2;
export const PLAYER_XP_PER_LEVEL = 1;

export const ENEMY_SPAWN_INTERVAL_MS = 1000;
export const RUN_TARGET_DURATION_MS = 420000;
export const RUN_ACTIVE_DELTA_CAP_MS = 100;
export const MINIBOSS_SPAWN_TIME_MS = 210000;
export const MINIBOSS_SPAWN_INTERVAL_MS = 210000;
export const BOSS_SPAWN_TIME_MS = 600000;
export const ELITE_SPAWN_INTERVAL_MS = 45000;
export const ENEMY_HIT_FLASH_MS = 80;
export const RUN_EVENT_ENCOUNTER_BUFFER_MS = 6000;
export const REWARD_TARGET_EVENT_WINDOW_START_MS = 100000;
export const REWARD_TARGET_EVENT_WINDOW_END_MS = 170000;
export const REWARD_TARGET_EVENT_DURATION_MS = 18000;
export const CHALLENGE_WAVE_EVENT_WINDOW_START_MS = 255000;
export const CHALLENGE_WAVE_EVENT_WINDOW_END_MS = 335000;
export const CHALLENGE_WAVE_EVENT_DURATION_MS = 16000;

export const XP_GEM_ATTRACT_SPEED = 520;

export const LEVEL_UP_FLASH_MS = 170;
export const LEVEL_UP_AUTO_PICK_MS = 15000;
export const PLAYER_HIT_SHAKE_DURATION_MS = 90;
export const PLAYER_HIT_SHAKE_INTENSITY = 0.0032;
export const ELITE_SPAWN_INDICATOR_MS = 650;
export const ENDING_FLASH_MS = 240;

export const AUDIO_MASTER_GAIN = 1;
export const AUDIO_NOTE_ATTACK_S = 0.04;
export const AUDIO_NOTE_FLOOR_GAIN = 0.001;

export const GOLD_REWARD_BASE = 14;
export const GOLD_REWARD_PER_LEVEL = 5;
export const GOLD_REWARD_PER_KILL_STEP = 5;
export const GOLD_REWARD_VICTORY_BONUS = 28;
